## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('move_together',
                                 ['pmip6', 'core', 'mobility', 'wifi', 'csma', 'olsr', 'flow-monitor'])
    obj.source = 'move_together.cc'